# Global Travis CI step definitions that will be used by all jobs unless
# explicitly overriden in the jobs.include matrix.

language: python
# We need sudo to install packages.
sudo: required
# NOTE: Apparently, Travis CI still hasn't strealined Python 3.7 support so
# one has to resort to using the "unofficial" Ubuntu Xenial Xerus (16.04 LTS)
# build environment and enable the "sudo" mode.
# More details here:
# - https://github.com/travis-ci/travis-ci/issues/9069#issuecomment-425720905
# - https://github.com/travis-ci/travis-ci/issues/9815
dist: xenial
python: "3.7"

before_install:
  - sudo apt-get install -y p7zip-full

install: pip install tox

script: tox -e $TOX_ENV

after_success:
 - pip install codecov
 - codecov -e TOX_ENV

 # Build stages.
jobs:
  include:
    - stage: test
      env: TOX_ENV=py36
      python: "3.6"
    - stage: test
      env: TOX_ENV=py37
    - stage: test
      env: TOX_ENV=docs
      before_install: skip
      after_success: skip
    - stage: test
      env: TOX_ENV=linters
      before_install: skip
      after_success: skip
    - stage: test
      env: TOX_ENV=packaging
      before_install: skip
      after_success: skip

    # NOTE: We undo/change all the global Travis CI step definitions to ensure
    # building of source and wheel distributions is performed in a clean
    # environment.
    - stage: release
      # Project uses setuptools_scm to determine the version from a SCM tag.
      install: pip install setuptools_scm
      script: skip
      before_install: skip
      # NOTE: Due to the way Travis CI currently works, setting
      # 'after_success: skip' would also result in skipping the deploy step.
      # A work-around is to execute a dummy echo command.
      # More info at: https://github.com/travis-ci/travis-ci/issues/8337.
      after_success: echo "Skipping..."
      deploy:
        provider: pypi
        user: genialis-bot
        password:
          secure: "bSjPceJjuTqdw8RY29lkRgxokK4V8z2V750KiSbwSSoujbec3IZK8JgQF7m/REwOPtiTtaQyt/nH9y0FdVZ7IBCU9y8x3n9rASrrkKTOuaz3k3Tx3w2hu8im3gyh9myhV1xop+BYkShG3wqnXczdUIpeD7TBiGPfHB5ZRLDc0OLtc1rZgO0qMN85PpylLpDH8pDv2rYucmDpXQ5uIFt9fBZTNSePaW5Gb4SeEWwnNjd4hpw2nLiOvEnQAa1SkM5yA4OH3iU6Ivxw0OSb/EkfDB0IzkR5L53Xg/f/rnInpRvtk0FIj5GglZVv+V8OrY54DmPqsr1cE8xstpNQd9IyJe6vlM5wIaa74CwtUgELHsMg5pt/EfN0R8ul+a5s8r+KTFcfSktZ3W/3fLlUTyh4I3pRyZppiOW68TQZSqsUuVTOcQsDykXcXCr9Qv/hSVvFCsiTKARjBXaaM71dATYI+b3EpMTB6e0eACNAQPdZTlhkP8htBoKh2uXAStfyzB5d+Q5T+neMgchtUOjZXI8PPsnZObO80D6hWOEcz/8//jp4+crL84KRgs0TFu5nG51z+MLB+hg2xoD3jZwYei3KeGQCbbiRJSmzUUQ/e/gCnejTlV/9zmxiCkonRL9xFtRpATb4cdCr04iw/p5HAXvm5s8NNr11Aix8Hl042R6iCs0="
        distributions: sdist bdist_wheel
        on:
          # Enable deploying tags. By default, Travis CI only deploys from the
          # master branch.
          tags: true
      # Only build releases for tags starting with a Semantic Versioning 2.0
      # compatible version.
      if: tag =~ ^\d+\.\d+\.\d+
